apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sdk
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: sdk
    newName: rg.fr-par.scw.cloud/djnd/sdk
    newTag: '351e026356d1bad9f911a7c8307a3df28f86e357'