apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sdk
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: sdk
    newName: rg.fr-par.scw.cloud/djnd/sdk
    newTag: 'a37baabd11413971c022852cfd48c2a4d5106954'